common-app:
  replicaCount: 1
  image:
    repository: 243060292047.dkr.ecr.eu-west-1.amazonaws.com/crf-demo1
    tag: "main-crf-demo1-b9fab37f"
  fullnameOverride: "crf-demo1"
  serviceAccount:
    create: true
    name: "crf-demo1"
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.cicd.grid2.maf.ae
    vault.security.banzaicloud.io/vault-role: crf-demo1-grid2-dev
    vault.security.banzaicloud.io/vault-path: kubernetes-eks-grid2-dev
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  service:
    type: ClusterIP
    targetPort: 3000
    port: 80
  ingress:
    enabled: true
    hosts:
      - host: crf-demo.dev.grid2.maf.ae
        paths:
          - path: /
            pathType: ImplementationSpecific
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  env:
    - name: PORT
      value: "3000"
    - name: NODE_ENV
      value: "development"
    - name: APP_NAME
      value: "crf-demo1"
    - name: API_RETAIL_API_KEY
      value: vault:secret/data/grid2-dev/crf-demo1/config#RETAIL_API_KEY
    - name: API_BASE_URL
      value: "https://retail-platform.mafrservicesstg.com/api/"
    - name: USER_ID
      value: vault:secret/data/grid2-dev/crf-demo1/config#USER_ID
